
{'date': 'Tue Aug 28 2018 15:59:23.135 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''
 module <string> line 4
  sala_0 = Sala(R_NORTE, R_LESTE, R_SUL, R_OESTE)
  ^
IndentationError: unexpected indent
'''},
{'date': 'Tue Aug 28 2018 16:01:27.554 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''
 module <string> line 8
  C2_SUL = C1_LESTE
  ^
IndentationError: unexpected indent
'''},
{'date': 'Tue Aug 28 2018 16:01:38.214 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''
 module <string> line 25
  sala_0 = Sala(R_NORTE, R_LESTE, R_SUL, R_OESTE)
  ^
IndentationError: unexpected indent
'''},
{'date': 'Tue Aug 28 2018 16:01:48.326 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 40
    sala.norte.vai()
NameError: name 'sala' is not defined
'''},
{'date': 'Tue Aug 28 2018 16:02:19.865 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 41
    sala_0.norte.vai()
NameError: name 'sala_0' is not defined
'''},
{'date': 'Tue Aug 28 2018 16:02:24.790 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 41
    sala_0.norte.vai()
NameError: name 'sala_0' is not defined
'''},
{'date': 'Tue Aug 28 2018 16:02:29.212 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 41
    sala_0.norte.vai()
NameError: name 'sala_0' is not defined
'''},
{'date': 'Tue Aug 28 2018 19:08:26.677 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 91
    Museu()
  module <module> line 67
    C_SUL = C1_SUL
NameError: name 'C1_SUL' is not defined
'''},
{'date': 'Tue Aug 28 2018 20:00:28.586 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''
 module <string> line 85
  if __name__ == '__main__':
                            ^
IndentationError: expected an indented block
'''},
{'date': 'Tue Aug 28 2018 20:10:43.554 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 91
    Museu()
  module <module> line 82
    Labirinto(sala_0, sala_1, sala_2, sala_3, sala_4)
NameError: name 'Labirinto' is not defined
'''},
{'date': 'Tue Aug 28 2018 20:11:46.586 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 91
    Museu()
  module <module> line 82
    Labirinto(sala_0, sala_1, sala_2, sala_3, sala_4)
NameError: name 'Labirinto' is not defined
'''},
{'date': 'Tue Aug 28 2018 20:28:49.383 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 93
    Museu()
  module <module> line 82
    Labirinto(sala_0, none, sala_1, sala_12, none)
NameError: name 'none' is not defined
'''},
{'date': 'Tue Aug 28 2018 20:29:58.784 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 93
    Museu()
  module <module> line 83
    Labirinto(sala_2, sala_1, sala_3, none, None)
NameError: name 'none' is not defined
'''},
{'date': 'Tue Aug 28 2018 23:16:22.406 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 102
    Museu()
  module <module> line 91
    dino = Elemento(img=DINO, tit="Dino", style=dict(left=50, top=160, width=200, height=200))
NameError: name 'Elemento' is not defined
'''},