
{'date': 'Sun Aug 12 2018 20:48:41.303 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 201
    Museu()
  module <module> line 119
    interrogacao_ = Elemento(interrogacao,cena= INVENTARIO, tit = "Help", 
NameError: name 'Elemento' is not defined
'''},
{'date': 'Sun Aug 12 2018 20:51:30.672 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 201
    Museu()
  module <module> line 119
    interrogacao_ = Elemento(interrogacao,cena= INVENTARIO, tit = "Help", 
NameError: name 'interrogacao' is not defined
'''},
{'date': 'Sun Aug 12 2018 20:56:35.230 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 202
    Museu()
  module <module> line 122
    INVENTARIO.pega (interrogacao)
AttributeError: 'Inventario' object has no attribute 'pega'
'''},
{'date': 'Sun Aug 12 2018 21:19:02.264 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 66
    class Codigo(Code):
  module <module> line 67
    def __init__(self, codigo="", topo="", cena=INVENTARIO, img="", vai=None, style=NS):
NameError: name 'NS' is not defined
'''},
{'date': 'Sun Aug 12 2018 21:19:28.135 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 211
    Museu()
  module <module> line 207
    [Codigo(cena = a,topo = b ,codigo= c, style= STYLE) for a, b , c in MENSAGENS]
  module <module> line 69
    a = html.A("&times;", Class="close", href="#")         
NameError: name 'html' is not defined
'''},
{'date': 'Sun Aug 12 2018 21:20:10.693 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 211
    Museu()
  module <module> line 207
    [Codigo(cena = a,topo = b ,codigo= c, style= STYLE) for a, b , c in MENSAGENS]
  module <module> line 69
    a = html.A("&times;", Class="close", href="#")         
NameError: name 'html' is not defined
'''},
{'date': 'Sun Aug 12 2018 21:22:10.229 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 66
    class Codigo(Code):
  module <module> line 67
    def __init__(self, codigo="", topo="", cena=INVENTARIO, img="", vai=None, style=NS):
NameError: name 'NS' is not defined
'''},
{'date': 'Sun Aug 12 2018 21:22:32.900 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 212
    Museu()
  module <module> line 208
    [Codigo(cena = a,topo = b ,codigo= c, style= STYLE) for a, b , c in MENSAGENS]
  module <module> line 69
    a = html.A("Ã—", Class="close", href="#")         
NameError: name 'html' is not defined
'''},
{'date': 'Sun Aug 12 2018 21:26:56.986 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''
 module <string> line 62
  from _spy.vitollino.main import Sala, STYLE, Codigo as Code, INVENTARIO, Elemento, NS, 
                                                                                         ^
SyntaxError: trailing comma not allowed without surrounding parentheses
'''},
{'date': 'Sun Aug 12 2018 21:50:21.110 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''
 module <string> line 131
  interrogacao = Elemento(interrogacao_,cena= INVENTARIO, tit = "Help", vai=recobra
                                                                                             ^
SyntaxError: invalid syntax
'''},
{'date': 'Sun Aug 12 2018 22:52:21.854 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 230
    Museu()
  module <module> line 145
    video=Video(source="https://www.w3schools.com/html/mov_bbb.mp4",width="320", height="240",top=0, left=0)
  module <module> line 79
    video=html.VIDEO(width=width, height=heigth,autoplay=True, style=dict(position="absolute", top=top, left=left))
NameError: name 'heigth' is not defined
'''},
{'date': 'Sun Aug 12 2018 23:33:03.321 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''
 module <string> line 168
  link_para_uma_imagem = "https://i.imgur.com/IPa06hM.jpg""""],
                                                               ^
SyntaxError: EOL while scanning string literal
'''},
{'date': 'Wed Aug 15 2018 09:37:04.1 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 246
    Museu()
  module <module> line 143
    dino = Elemento(img=DINO, tit="Dino", style=dict(left=50, top=160, width=200, height=200))
NameError: name 'DINO' is not defined
'''},
{'date': 'Wed Aug 15 2018 09:37:50.310 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 247
    Museu()
  module <module> line 146
    dinotexto = Texto(sala_2.leste, "e ai,colega, tudo tranks?")
NameError: name 'Texto' is not defined
'''},
{'date': 'Wed Aug 15 2018 10:54:47.648 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''
 module <string> line 246
  STYLE = dict(width=400,heigth="250px",left=400,top=100,"visibility": "hidden", "opacity": 0)
                                                                      ^
SyntaxError: invalid syntax
'''},
{'date': 'Wed Aug 15 2018 21:22:44.888 GMt-0300 (HorÃ¡rio PadrÃ£o de BrasÃ­lia) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 252
    Museu()
  module <module> line 248
    [Codigo(cena = a,topo = b ,codigo= c, style= STYLE) for a, b , c in MENSAGENS]
  module <module> line 73
    __init__= self(hidden)
TypeError: 'Codigo' object is not callable
'''},
{'date': 'Wed Aug 15 2018 21:23:24.967 GMt-0300 (HorÃ¡rio PadrÃ£o de BrasÃ­lia) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 252
    Museu()
  module <module> line 248
    [Codigo(cena = a,topo = b ,codigo= c, style= STYLE) for a, b , c in MENSAGENS]
  module <module> line 73
    __init__= self(hidden)
TypeError: 'Codigo' object is not callable
'''},
{'date': 'Wed Aug 15 2018 21:37:19.499 GMt-0300 (HorÃ¡rio PadrÃ£o de BrasÃ­lia) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 257
    Museu()
  module <module> line 162
    MENSAGEM=msg
NameError: name 'msg' is not defined
'''},
{'date': 'Wed Aug 15 2018 21:38:15.848 GMt-0300 (HorÃ¡rio PadrÃ£o de BrasÃ­lia) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 258
    Museu()
  module <module> line 164
    self.onclick=msg._open
NameError: name 'msg' is not defined
'''},
{'date': 'Wed Aug 15 2018 21:40:25.480 GMt-0300 (HorÃ¡rio PadrÃ£o de BrasÃ­lia) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 258
    Museu()
  module <module> line 164
    self.onclick=MENSAGEM._open
NameError: name 'MENSAGEM' is not defined
'''},
{'date': 'Wed Aug 15 2018 21:41:27.744 GMt-0300 (HorÃ¡rio PadrÃ£o de BrasÃ­lia) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 258
    Museu()
  module <module> line 164
    self.onclick= MENSAGEM._open
NameError: name 'MENSAGEM' is not defined
'''},
{'date': 'Wed Aug 15 2018 21:43:38.605 GMt-0300 (HorÃ¡rio PadrÃ£o de BrasÃ­lia) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 258
    Museu()
  module <module> line 164
    self.onclick= MENSAGENS._open
UnboundLocalError: local variable 'MENSAGENS' referenced before assignment
'''},
{'date': 'Wed Aug 15 2018 21:44:39.187 GMt-0300 (HorÃ¡rio PadrÃ£o de BrasÃ­lia) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 63
    from _spy.vitollino.main import Sala, STYLE,MENSAGENS, Codigo as Code, INVENTARIO, Elemento, NS,Texto
ImportError: cannot import name 'MENSAGENS'

ImportError
Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 264
    action()
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 63
    from _spy.vitollino.main import Sala, STYLE,MENSAGENS, Codigo as Code, INVENTARIO, Elemento, NS,Texto
'''},