
{'date': 'Mon Sep 24 2018 11:24:11.549 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''
 module <string> line 106
  sala_0 = Sala(S0_NORTE, S0_LESTE, S0_SUL, S0_OESTE)
  ^
IndentationError: unexpected indent
'''},
{'date': 'Mon Sep 24 2018 11:24:46.69 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''
 module <string> line 103
  sala_0 = Sala(S0_NORTE, S0_LESTE, S0_SUL, S0_OESTE)
  ^
IndentationError: unexpected indent
'''},
{'date': 'Mon Sep 24 2018 11:25:37.957 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''
 module <string> line 104
  sala_1 = Sala(S1_NORTE, S1_LESTE, S1_SUL, S1_OEST
                                                     ^
SyntaxError: invalid syntax
'''},
{'date': 'Mon Sep 24 2018 15:44:10.818 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''
 module <string> line 76
  sala_0 = Sala(S0_NORTE, S0_LESTE, S0_SUL, S0_OESTE)
  ^
IndentationError: unexpected indent
'''},
{'date': 'Mon Sep 24 2018 15:45:33.150 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''
 module <string> line 76
  sala_0 = Sala(S0_NORTE, S0_LESTE, S0_SUL, S0_OESTE)
  ^
IndentationError: unexpected indent
'''},
{'date': 'Mon Sep 24 2018 15:45:45.269 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''
 module <string> line 76
  sala_0 = Sala(S0_NORTE, S0_LESTE, S0_SUL, S0_OESTE)
  ^
IndentationError: unexpected indent
'''},
{'date': 'Mon Sep 24 2018 15:45:59.230 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''
 module <string> line 77
  sala_0 = Sala(S0_NORTE, S0_LESTE, S0_SUL, S0_OESTE)
  ^
IndentationError: unexpected indent
'''},
{'date': 'Mon Sep 24 2018 15:53:16.721 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''
 module <string> line 101
  Labirinto(sala_0, None, sala_1, sala_12, None)
  ^
IndentationError: unexpected indent
'''},
{'date': 'Mon Sep 24 2018 15:53:40.65 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 108
    Museu()
  module <module> line 93
    Labirinto(sala_0, None, sala_1, sala_12, None)
NameError: name 'sala_12' is not defined
'''},
{'date': 'Mon Sep 24 2018 15:53:50.589 GMt-0300 (-03) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 160
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 306
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 278
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 295
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 108
    Museu()
  module <module> line 93
    Labirinto(sala_0, None, sala_1, sala_12, None)
NameError: name 'sala_12' is not defined
'''},